# Generated by Django 3.2.8 on 2021-11-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='providerType',
            field=models.CharField(choices=[('doctors', 'Doctors'), ('nurses', 'Nurses'), ('therapists', 'Therapists'), ('dentists', 'Dentists'), ('pharmacists', 'Pharmacists'), ('physicalTherapists', 'Physical Therapists'), ('medLabScientist', 'Medical Laboratory Scientists'), ('hospitals', 'Hospitals'), ('careHome', 'Care Homes'), ('ophthalmologists', 'Ophthalmologists'), ('podiatrists', 'Podiatrists'), ('others', 'Others')], max_length=255),
        ),
    ]
