# Generated by Django 3.2.8 on 2021-11-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_providertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='providerType',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('therapist', 'Therapist'), ('dentist', 'Dentist'), ('pharmacist', 'Pharmacist'), ('physicalTherapist', 'Physical Therapist'), ('medLabScientist', 'Medical Laboratory Scientist'), ('hospital', 'Hospital'), ('careHome', 'Care Home'), ('ophthalmologist', 'Ophthalmologist'), ('podiatrist', 'Podiatrist'), ('other', 'Other')], max_length=255),
        ),
    ]
