# Generated by Django 3.2.8 on 2021-11-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointmentDate',
        ),
    ]
