# Generated by Django 3.2.8 on 2021-11-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
