# Generated by Django 3.2.8 on 2021-10-24 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider')], max_length=255)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
    ]
